### ISSUE TITLE
로그인한 유저로 기능하도록 변경

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#11]
현재 로그인해도 로그인한아이디와 별개로 학번이 20150390인 아이디를 끌어다쓰고있음 -> 로그인한유저로 기능하게 변경해야됨

**Comment by a1sams1a** [comment]
학번 없는 사람도 고려해 주세요. git clone 했는데 메인페이지부터 오류 ㅜㅜ

**Comment by jiggum** [comment]
아직기능 구현이 안되서..
학번 20150390인 유저만들어서 테스트해주세요

**Comment by a1sams1a** [comment]
SPARCS SSO /api/token/info/의 kaist_info -> ku_std_no 정보를 사용하여 학번을 얻을 수 있습니다.

**Comment by isyangban** [comment]
이번 주 내로 처리하겠습니다.

**Comment by isyangban** [comment]
구현은 했고, OTL+ 스팍스 sso  등록되면 테스트 해볼 수 있습니다.
