### ISSUE TITLE
Color Class - 시간표 블록 색의 관한 정책과 구현

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#110]
1. 조건
   시간표의 이웃한 블록은 다른 색이고, 한 코스의 색은 삭제했다가 추가해도, 여러 시간표에
   걸쳐서도 모두 동일하다.
2. 정책
   가능한 색을 N 개 만들어 두고 추가한(했던) 코스의 가짓수가 N 개 이하면 완벽히 이웃 구분 가능하면서 동일 코스 동일 색 조건을 보장한다.
3. 구현 - 컬러 Class Spec       //강원아 속성들 설명하는 주석 좀 달아줘 
   class ColorClass
   누구
   언제
   뭔 과목
   색

**Comment by kangwon** [comment]
class BlockColor
  누구 (사람에 따라 색상이 유지되어야 하므로)
  언제 (lecture 별이 아닌 course 별로 구분해달라는 요청이 있어서 필요합니다.)
  뭔 과목 (course)
  색 (integer로 해 두고, enum에 파일 하나 만들어서 매칭시키면 어떨까 합니다.)

사용은
1. 사용자가 시간표에 과목을 집어넣음
2. 그 학기, 그 과목에 대한 색상을 결정해서 저장함
3. 가장 최근의 데이터를 색상의 수만큼 불러 와서 사용 (ex 색상 수 = 30 일 때 가장 최근 30개의 데이터만 불러옴.)
-> 31번째부터 같은 과목에 다른 색상이 부여될 수 있음

2번 과정에서 색상 결정은 다음에 논의하도록 합시다.

BlockColor 테이블에 쓸모 없는 데이터들(31번째 이상으로 오래된 설정)이 많이 쌓이게 되는 방법이지만, 굳이 지울필요 있나 해서 지우는 과정은 생략했습니다.

**Comment by zealotzealot** [comment]
재논의한 결과 course(lecture가 아님)의 고유 id를 색상의 갯수만큼 나눈 나머지로 색상을 정하기로 했습니다. 이유는 다음과 같습니다.
- 구현이 간편하며 별도의 db table과 query를 요구하지 않아 성능상 유리함
- 유저에 관계없이 같은 색상이기 때문에 타인과 시간표를 비교하기 편리함
- 색상의 수가 일반적으로 추가하는 과목의 수에 비해 충분히 많음
- 한 시간표 내 색상이 겹치는 것을 보안하기 위한 다른 인터페이스적 장치가 다수 마련되어 있음
