### ISSUE TITLE
타임테이블 필터 검색

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#111]
필터 검색 : 거의 구오티엘과 그대로 유지하되 다음의 개선 사항 추가
- 학과 선택 dropdown에 직접 학과를 입력할 수도 있게, 크롬 식의 자동 완성을 채택한다. 
- 필터 초기화 버튼(모든 필터를 ALL로) 추가
- OTLPLUS의 필터와 잘 통합할 방법?
- 영어 강의 필터 추가(제안)

**Comment by zealotzealot** [comment]
#221
