### ISSUE TITLE
타임테이블 시간표 블록을 누르면 과목의 상세한 정보 표시

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#116]
기존에는 블록에 마우스 호버 시에 과목의 상세정보와 오티엘 평가점수 평균등을 보여줬는데 

이걸 블록 클릭했을 때로 변경

*평균 강의 평가 점수와 상세한 정보를 이웃하여 표시(현재는 따로 떨어져 있음)

**Comment by ashe-sparcs** [comment]
지금 생각해보면 이게 마우스 포인터 빠져나가기 어려운 문제는 해결 가능한데 일일이 클릭해줘야 하니까 코스트가 좀 높은게 아닌가 하는 생각이 듭니다.

**Comment by zealotzealot** [comment]
#234
