### ISSUE TITLE
타임테이블 드래그 검색

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#117]
시간표 상에서 드래그한 시간대에 해당하는 과목들을 검색
- 제안 : 필터 적용 여부(개인이 Customize, 기본값 false?)
- 모바일에서 드래그 검색 사용가능하게 하기 위한 제안:
  ![kakaotalk_photo_2016-07-16-11-39-15](https://cloud.githubusercontent.com/assets/15705385/16892335/3f238e5a-4b4a-11e6-9670-bcb26309d811.jpeg)
  안드로이드/아이폰 텍스트 영역 설정 시처럼(사진참조) 시간표를 오랫동안 터치하고 있으면 영역을 선택할 수 있도록

**Comment by jihoon-ko** [comment]
일단 json으로 데이터 얻어오는 거는 만들어볼게요

**Comment by zealotzealot** [comment]
#243
