### ISSUE TITLE
타임테이블 Custom 일정 추가 

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#119]
- 시간표 영역 드래그 시 검색은 검색대로 나오되 블록이 만들어져 X표 추가하듯 +표가 추가됨
- 그걸 누르면 커스텀 일정 추가 가능(일정 이름, 장소 등등 기입)
- 주말도 보여줘야 한다? 시간표 공간 확보가 필요.

**Comment by zealotzealot** [comment]
추가하지 않는 것으로 결정하였습니다.
