### ISSUE TITLE
후기 아이디로 접근할수 있는 페이지작성

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#12]
후기마다 url부여, 후기클릭시 ~/~/~/후기_id url로 이동후, 그후기 하나만 보여주는 페이지

**Comment by taehyun9** [comment]
575364f59c428fad0472a2a6d304d53422afebad

임시로 view 구현해두습니다.
review 나오는 부분 확인 후에 review를 클릭하거나 review id를 사용해 url로 직접 접근할 경우 review 하나만 나오도록 수정할 예정
