### ISSUE TITLE
타임테이블 시간표 보여주기

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#121]
블록 추가 : 리스트에서 해당하는 과목을 클릭
블록 삭제 : X 표 클릭
시간표 블록에 X 표 넣기 : 마우스 올릴 시 두 블록 모두 하이라이트하고 X 표는 마우스 올린 블록의 우측 상단에만

**Comment by ashe-sparcs** [comment]
ashe is assigned.

**Comment by ashe-sparcs** [comment]
다음을 전제로 구현하겠습니다.
1. 유저를 배제합니다(즉 유저가 하나라고 가정합니다) 시간표 url을 따로 파서 그곳에 접속하면 세개의 timetable id를 선택할 수 있어서 누르면 그 id에 해당하는 시간표가 출력됩니다.
2. 추가와 삭제는 차차 구현합니다. 우선은 장고를 통해 직접 데이터를 넣고 빼겠습니다.

**Comment by zealotzealot** [comment]
#226
