### ISSUE TITLE
새로운 model migration 오류 해결하기

### ISSUE THREAD

**Issue by kangwon** [sparcs-kaist/otlplus#124]
pull request #109 merge --> OK
 후 test DB에 migrate 하기
- 실서버 디비를 수정된 모델에 맞도록 스키마(틀) 수정. 
- 학사 디비를 불러오는 스크립트 수정.
- 완성된 mysql 디비를

1. 실서버 디비에 마이그레이션을 성공시키기(새로 짠 모델을 수정해서, 아님 어떻게든 제발 ㅜ) 

1-1. mysql을 실행시켜서 일일이 표에 내용을 적어넣는다(test db 이용).

2. 빈 디비를 만들고 기존 정보를 가져오는 스크립트 만들기

방법 1,2 중 각자 임의로 정해서 시도해보기. 각 방식별로 이슈를 나눠도 좋음.

**Comment by ashe-sparcs** [comment]
백엔드 개발을 하려면 이게 선행되어야 해서 이걸 최우선으로 해결하도록 합시다.

**Comment by kangwon** [comment]
일단 해결했습니다.

1. 기존 DB(comment들이 쌓이고 있는 현재 운영중인 otlplus DB. DB server(otlplus.sparcs.org:3306)에서의 DB name은 `otlplus`)를 dump한다. (dump한 파일을 'tmp.sql'라 하겠다.)
2. 비어있는 DB를 생성(DB name은 'tmp'라 하겠다.) 

   `CREATE DATABASE tmp;`
3. tmp DB에 최신 모델을 makemigrations한 뒤, migrate한다. 

   `git pull `
   `git checkout tiimetable `
   `python manage.py makemigrations main review session subject timetable `
   `python manage.py migrate`
4. tmp DB에 다음 sql문을 실행한다.
   
   ```
BEGIN;
ALTER TABLE `session_userprofile` ADD `department_id` integer NOT NULL;
ALTER TABLE `session_userprofile` ADD `email` varchar(255) NULL;
ALTER TABLE `session_userprofile` ADD CONSTRAINT `session_userprof_department_id_b96d3390_fk_subject_department_id` FOREIGN KEY (`department_id`) REFERENCES `subject_department` (`id`);
ALTER TABLE `subject_lecture` ADD `syllabus` varchar(260) NULL;
COMMIT;
   ```

**Comment by kangwon** [comment]
4번 단계에서 'session_userprof_department_id_b96d3390_fk_subject_department_id' 부분은
`python manage.py sqlmigrate session [migrate name]` 으로 확인해 봐야 할 것 같아요.

그리고 테스트해보니까 auth_user에는 제 계정이 있지만 그에 해당하는 session_userprofile이 없는 문제가 있었습니다. views.py의 버그인지, 제 계정의 문제인지, 아니면 DB를 만지작 거릴 때 생긴 문제인지 확인해 봐야 할 것 같습니다. 다른 분들도 이거 한 번 테스트해보고 결과 코멘트로 남겨주시기 바랍니다.

**Comment by jihoon-ko** [comment]
로컬의 mysql에서 같은 것을 하려고 했더니 중간에 '글자수가 너무 많다'라는 에러가 뜨네요 ㅠㅠ

**Comment by kangwon** [comment]
session_userprofile에 department_id와 email이 새로 추가되는 field입니다. syllabus도 subject_lecture에 새로 추가된 field고요. 그래서 이 부분에서 주로 에러가 날 거에요.

어쨌든, 어느 단계에서 문제가 생기죠?

**Comment by jihoon-ko** [comment]
3번 단계에서 migrate 할 때 글자수 초과 때문에 문제가 생깁니다

**Comment by kangwon** [comment]
왜 그런지 모르겠네요. 일단 개발용 DB를 사용하도록 하죠.

**Comment by kangwon** [comment]
4번 과정에서 
```
ALTER TABLE `session_userprofile` ADD `department_id` integer NOT NULL;
```
->
```
ALTER TABLE `session_userprofile` ADD `department_id` integer NULL;
```
로 수정합니다.
