### ISSUE TITLE
[과목사전] 제안 : 검색 시 코스가 맨 위에 그 다음부터 후기가 바로 나오게끔 하기

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#128]
@jiggum 의 제안입니다. otl 과목사전 검색 시 현재는 코스만 나오는데 바로 후기를 보고 싶은 사람이 

많다고 생각되어 해당되는 코스가 맨 위에 나오고 그 밑으로는 후기가 나오도록 하기.

**Comment by ashe-sparcs** [comment]
제안한 사람이 하도록 한다.
