### ISSUE TITLE
[타임테이블] 타임테이블 프론트엔드

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#131]
디자인도 모델도 나오지 않았지만 우선 부트스트랩을 써서 앞단이라도 짜봅시다.
1. 과목리스트
   과목 리스트 보여주기
   거의 그대로 유지
   OTL 평균 평가 점수 우수한 과목에 뱃지 달아주기 점수 낮은 과목은 그냥 두기.
   제안 : 과목 리스트 위에서 마우스 휠 돌리면 (리스트의) 다음 페이지로 이동.
   *보여줄 과목은 적당히 몇개를 넣어주세요. 이름만 있으면 됩니다. 페이지네이션도 해주세요.
2. 시간표와 블록.
   블록 추가 : 리스트에서 해당하는 과목을 클릭
   블록 삭제 : X 표 클릭
   시간표 블록에 X 표 넣기 : 마우스 올릴 시 두 블록 모두 하이라이트하고 X 표는 마우스 올린 블록의 우측 상단에만
   *디비에 적용할 필요는 없고 나타났다가 사라지는 것만 구현해주세요.
3. 시간표 공유
   시간표에 해당하는 영역(실제로 시간표는 없지만)을 이미지 파일로 저장하기/저장한 이미지파일 SNS에 업로드 등등을 해봅시다.
4. 커스텀 일정 추가
   디비에 저장되지는 않고 보여주기만 되는 커스텀 일정 추가 기능을 넣어봅시다.
5. 과목 블록 클릭시 상세정보 
   상세정보를 디비에서 불러오지 말고 직접 입력해서 보여주기만 가능한 상세정보 뷰를 짜봅시다.

이슈를 여러개로 각자 나누셔도 되고 여기에 여러명이 assign되어도 됩니다. 풀리퀘만 하나씩 날려주시면.

**Comment by jo1996jo** [comment]
모양만 갖춘 프론트를 만들겠습니다

**Comment by zealotzealot** [comment]
#206
