### ISSUE TITLE
letsencrypt refresh cron에 올리기

### ISSUE THREAD

**Issue by kangwon** [sparcs-kaist/otlplus#136]
지금 이메일이 온걸 보니까 letsencrypt 자동화가 되어있지 않은 모양이군요.

이걸 cron에 올려서 자동으로 해야할 필요가 있지 싶습니다.

**Comment by a1sams1a** [comment]
sudo 없는 samjo 계정 만들어주시면 확인 뒤 자동화하도록 하겠습니다.

**Comment by ashe-sparcs** [comment]
ㅇㅋ 지금 만들게

**Comment by a1sams1a** [comment]
다음과 같이 처리하였음
0. root에 zsh 및 oh-my-zsh 설치
1. 즉시 인증서 갱신
2. 갱신용 스크립트 /root/renewal.sh 작성
3. 갱신 테스트용 스크립트 /root/renewal.test.sh 작성
4. root의 cron으로 매 짝수 달 1일 새벽 4시 갱신 스크립트가 실행되도록 함
