### ISSUE TITLE
SPARCS SSO 로그인 후 원래 보던 페이지로 리다이렉트

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#138]
스마트폰으로 해본건데 피시에서도 같을거라고 생각합니다. 로그인 후 리다이렉트가 원래 보던 페이지로 됐으면 좋겠습니다

**Comment by a1sams1a** [comment]
해당 기능은 SPARCS SSO API v2에 추가될 내용입니다. 현재 SPARCS SSO Beta 서버 (ssobeta.sparcs.org)에서 API v2를 사용할 수 있으며, 1주일 내에 개발 문서를 제작하여 배포할 예정입니다.

**Comment by a1sams1a** [comment]
@kangwon 이 이슈 처리부탁드립니다.
