### ISSUE TITLE
[과목사전] 후기에 교수님 이름, 연도 이외에 학기도 써주기

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#139]
사진 참조해주세요. 이게 원래 정책을 그렇게 하기로 한건지는 기억이 안나는데 학기도 있는게(표시한 부분을 김광년 2014 봄) 훨씬 알아보기 좋을 것 같습니다. 김광년 ㅂㄷㅂㄷ
<img width="1280" alt="2016-07-21 10 24 54" src="https://cloud.githubusercontent.com/assets/15705385/17008627/ea7df81c-4f2d-11e6-8a95-1257a4ba6cf4.png">

**Comment by jihoon-ko** [comment]
![2016-07-27 01-58-46](https://cloud.githubusercontent.com/assets/15546366/17147442/c49f009a-539d-11e6-9bb5-cec16afb26f5.png)
