### ISSUE TITLE
[과목사전] SPARCS SSO 사망 시 예외처리

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#144]
SPARCS SSO가 사망 시에 새로 로그인 시도하면 500 에러 뜨는데 이거 예외처리해서 로그인 막고 읽기 전용으로만

볼 수 있도록 하기.

**Comment by isyangban** [comment]
읽기 전용으로만 볼 수 있게 한다는 게 정확이 무슨 의미인지 모르겠네요.

**Comment by ashe-sparcs** [comment]
@isyangban 로그인 안했을 때는 후기 작성이 불가능한데, 그와 같은 상태로 이용하도록 한다는 뜻입니다.
