### ISSUE TITLE
[과목사전] 후기 (자동)임시저장 기능

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#145]
후기도 이메일 작성 시처럼 임시저장 기능이 있었으면 좋겠습니다. 

optional로 중간에 서버 연결이 끊기는 등의 상황에 대비하여 일정 시간 간격으로 자동 임시저장이 있어도 좋을 것

같습니다.

**Comment by zealotzealot** [comment]
#250 으로 대체합니다.
