### ISSUE TITLE
SPARCS SSO v2 연동

### ISSUE THREAD

**Issue by kangwon** [sparcs-kaist/otlplus#146]
SPARCS SSO가 업그레이드 되면서 session 쪽 코드가 수정될 필요가 생겼습니다.

**Comment by kangwon** [comment]
session 쪽 이슈이지만, 지금 session 코드를 끌어다가 수정해 놓으면 merge할 때 conflict가 많이 일어날 것 같네요. 현재 최신인 timetable branch에서 작업하도록 하겠습니다.

**Comment by kangwon** [comment]
로그아웃한 다음에는 어느 페이지로 가는게 좋을까요?
1. 원래 있던 그 페이지 (로그인과 같음)
2. 메인 페이지

**Comment by kangwon** [comment]
현재는 메인 페이지네요.
일단 메인 페이지로 만들게요.

**Comment by ashe-sparcs** [comment]
@kangwon timetable이 최신이라고 해야되나 그거 갈라진 이후로도 리뷰 작업된거 좀 있어서 리뷰에도 해줘야 할듯? 아 어찌해도 컨플릭트 마구 날거 같다 두렵다 깃초보는..

**Comment by kangwon** [comment]
저런...

나중에 클로즈를 잊지 않기 위한 연관 이슈
issue #138
