### ISSUE TITLE
ERROR (External IP) Invalid HTTP_HOST header를 fix 하기

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#151]
메일링 참조, 해킹 공격으로 의심됨. 어느 ip인지 조회해서 지오아이피 쳐보고 의심 가는 곳이면 차단하기.

**Comment by a1sams1a** [comment]
1. HTTP에는 어느 사이트의 정보를 요청했는지 표시하기 위한 Host Header가 있음
2. django는 보안을 위해 DEBUG=False인 경우 미리 설정된 Host와 일치하는 경우에만 요청을 처리함
3. 해당 메일은 단순히 ip가 host인 경우이므로, domain name 없이 ip로 들어왔을 때 발생하는 경고 메시지임
4. 웹 아카이빙 서비스나 ip 조회 서비스(예: https://db-ip.com/) 등은 주기적으로 모든 ipv4를 scan하여 정보를 수집함
5. 따라서, 단순히 ip 주소로 접속한 경고 메일링이 온 경우 이를 해킹이라 할 수 없으며, 추가적인 조사가 필요 없다고 생각됨
6. 다만, 쓸데 없는 메일링을 받지 않기 위해 ip 주소로 접속한 경우 도메인 주소로 경고 없이 redirect되도록 하는 설정이 필요하다고 생각됨

**Comment by ashe-sparcs** [comment]
샤형이 로그보니까 툴써서 사이트 관리자 권한 따려고 시도한게 있다던데 다른 메일이었나

**Comment by a1sams1a** [comment]
해당 메일을 보내주시면 확인해보도록 하겠습니다.

**Comment by ashe-sparcs** [comment]
해당 메일 포워드했습니다.

**Comment by a1sams1a** [comment]
1. ip 91.219.237.143에서 온 요청은 자동화된 공격 도구를 사용한 것으로 보임
2. ip 199.115.117.99에서 온 요청은 그 자체로는 공격이라고 볼 수 없다고 판단됨

**Comment by ashe-sparcs** [comment]
1번에 해당하는 아이피 차단하도록 하겠습니다.

**Comment by ashe-sparcs** [comment]
1번에 해당하는 아이피 차단했습니다.
