### ISSUE TITLE
ERROR (EXTERNAL IP): internal server error DoesNotExist at ... 에러 메일 처리

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#152]

**Comment by kangwon** [comment]
이거 내용이 뭔지 잘 모르겠는데, 에러 메일 쪽은 대부분 해결된 걸로 알고 있습니다.
혹시 이 이슈 아직 해결이 안 되었다면 설명 좀 달아주시고, 해결된 이슈라면 이슈 닫아주세요.

**Comment by Shavakan** [comment]
방금도 날아왔습니다. 해결 안된게 아닐까 싶어요
