### ISSUE TITLE
로그인이 필요한 페이지(마이페이지 등)에서 로그아웃하면 SPARCS SSO 로그인 창이 뜨는 문제 해결

### ISSUE THREAD

**Issue by kangwon** [sparcs-kaist/otlplus#157]
로그인이 필요한 곳에서 로그아웃 시 
redirect to login url -> redirect to SPARCS SSO -> SPARCS SSO login page
를 거쳐 바로 SSO 로그인창이 뜹니다.

사용자가 별로 원하는 바는 아닐 것이라 생각해 해결이 필요해 보입니다.

해결책 후보
1. "SPARCS SSO로 로그인해주세요." 페이지를 만든다.
2. 해당 일부 페이지는 메인 페이지로 이동하도록 만든다.
3. 다른 멋진 방안을 코멘트로 단다.

**Comment by jihoon-ko** [comment]
제가 해 봤을 때에는 후기작성페이지나 마이페이지 같은 곳에서 로그아웃하면 메인 페이지로 돌아가길래 문제 없다고 판단했었는데, 어떤 페이지에서 로그아웃을 하면 SSO 로그인 창이 뜨나요?

**Comment by kangwon** [comment]
sparcs sso 업그레이드를 하면서 로그아웃하면 원래 있던 페이지로 이동하는 기능이 추가되었습니다.

따라서 SSO v2를 적용한 뒤, 마이페이지에서 로그아웃 하게 되면 로그아웃된 상태로 마이페이지에 접근하게 되고, login url을 따라 결국 SPARCS SSO login  page로 이동하게 됩니다.

**Comment by kangwon** [comment]
현재 구현되어있는 상태(로그아웃 하자마자 바로 SSO 페이지로 이동하는 상태)에 다른 분들은 별다른 불만이 없는 듯 하여 기획상 의도된 상태라고 보겠습니다. 따라서 별다른 해결책을 적용하지 않고 이슈 닫겠습니다.
