### ISSUE TITLE
장고 1.10으로 업데이트

### ISSUE THREAD

**Issue by sorrykim** [sparcs-kaist/otlplus#159]
당장은 아니지만 현버전 1.9-->1.10 으로 올려야겠습니다. 

런서버했을 때 보셨듯이 1.10으로 올라가면서 호환안된다고 워닝띄운게 꽤 많습니다 ㅜㅜ

이놈들 고치고 장고 업데이트 해야합니다.

**Comment by jihoon-ko** [comment]
일단 Warning의 오류를 찾아보고 없애볼게요

**Comment by jihoon-ko** [comment]
Django 1.10에서는 import-scholardb.py에 문제가 있는 것 같네요 ㅠㅠ

**Comment by zealotzealot** [comment]
#494
