### ISSUE TITLE
[타임테이블] 되돌리기 기능

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#167]
되돌리기 기능이 있으면 좋을 것 같습니다. 근데 구현하기 매우 빡칠듯..

**Comment by kangwon** [comment]
되돌리기 기능이 어떤 기능인가요?

**Comment by ashe-sparcs** [comment]
추가했다가 삭제로 되돌리는 것은 간단하니까 그 반대, 즉 삭제했던 것을 다시 되살리는 것만 하면 될거 같습니다.

**Comment by kangwon** [comment]
그럼 삭제할 때 다른 DB에다가 빼 놓던지, deleted field를 추가하던지 하면 되는 겁니까?

**Comment by ashe-sparcs** [comment]
모델 수정없이 가능한가요? 가능하다면 그렇게 하는 편이 좋을 것 같습니다.

**Comment by a1sams1a** [comment]
1. 기존 모델 수정은 필요없는거 같고 새로 모델하나 파야할거 같...
2. 로그인이 유지될 경우 session에 넣어서 저장할 수도 있
3. redis 같은걸 끼얹나?

**Comment by kangwon** [comment]
2번이 타당해 보입니다. 보통 undo 기능이 로그아웃하고 다시 들어와도 작동할 거라고 생각은 안 하니, 굳이 DB에 따로 저장할 필요는 없을 것 같아요.
