### ISSUE TITLE
[공통] 오티엘플러스 공용 구글 계정 복구 메일 변경

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#169]
우선 메일링을 timetable 개발자 용으로 새로 만들어서(이걸 sysop과 동일하게 쓰면 될듯 #168 참조) 

이걸 복구메일로 하는게 맞는듯

**Comment by kangwon** [comment]
복구 메일이 뭔가요?

**Comment by ashe-sparcs** [comment]
음 제가 무슨 의도로 이걸 썼는지 모르겠는데 현재 오티엘플러스 공용 계정 로그인하면 매번 다른 기기에서 로그인했다고 메일 오는 것 같아서 조금 귀찮은 것 같습니다.
