### ISSUE TITLE
[과목사전] 사랑받는 후기 최대 높이 고정

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#173]
현재 오티엘플러스 메인페이지에 사랑받는 후기들 있는데

내용 길이에 상관없이 3개가 나오도록 되어있는데 후기별로 길이 차이가 많이나서

전공과 교양의 길이가 심하게 달라지는 경우가 빈번히 발생합니다(주로 교양쪽이 많이 긺)

보기 안예뻐서 최대 높이를 설정해두고 길이가 그 이상이면 ... 으로 하던지 디자인을 정해서

수정하는 것을 제안합니다.

**Comment by zealotzealot** [comment]
리액트 변환으로 종료
