### ISSUE TITLE
[과목사전] 일부 상황에서 loadOnScroll 안됨

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#190]
![image](https://cloud.githubusercontent.com/assets/15705385/20648904/7452cf08-b4f6-11e6-96d5-64a67eb80747.png)
위 상황에서 loadOnScroll이 안됩니다.

또 안되는 상황 있으면 코멘트로 달아주세요.

**Comment by jihoon-ko** [comment]
See Pull Request #200
