### ISSUE TITLE
[과목사전] 신인식 os 평균 평점 안나오는 버그(BugTL)

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#191]
![image](https://cloud.githubusercontent.com/assets/15705385/20649031/305b3210-b4f9-11e6-9246-93eeab38a1f8.png)

![image](https://cloud.githubusercontent.com/assets/15705385/20649027/1e5234ba-b4f9-11e6-8170-3ee9f0471340.png)

![image](https://cloud.githubusercontent.com/assets/15705385/20649059/bfe338d8-b4f9-11e6-893e-9243644bd5b4.png)

코스 페이지에서 교수님을 선택하면 코스에 속하는 렉쳐 후기들 중에서 그 교수님에 해당하는 렉쳐들의 평가 평균이 나와야 합니다. 그런데 일부 과목에 대해서 그것이 누락되어 있습니다.
예를들어 이미지와 같이 송os는 평균이 나오는데 신os는 평균이 안나옵니다. 마지막 사진은 허아키인데 이 과목 평균 평점도 나오지 않습니다.

**Comment by zealotzealot** [comment]
#227
