### ISSUE TITLE
[타임테이블] 코스 중에서 특정 교수님에 해당하는 렉쳐 평점 평균 구하기

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#192]
예를 들어 지금은 os과목 전체 후기에 대해서 평균 평점을 계산하는데 송준화 교수님의 os 과목 전체 후기에 대하여 평균 평점을 계산하여 타임테이블 좌측 상단에 그 점수를 표시해야 합니다. 과목사전에 이미 구현되어 있으므로 그 코드를 참조하면 좋을 것 같습니다. 근데 그 코드에 버그가 있을 수 있습니다. #191 을 해결한후에 가져다 써야 합니다.

**Comment by zealotzealot** [comment]
#248
