### ISSUE TITLE
Review delete 알고리즘 변경

### ISSUE THREAD

**Issue by Shavakan** [sparcs-kaist/otlplus#194]
현재의 방식처럼 실제로 DB에서 삭제를 하는 것은 기록 관리 측면에서 문제가 있다.

Arara에서 하는 것처럼 is_deleted 필드를 추가하고 render를 다르게 한다든가 등의 방법을 논의해보자.

삭제처리된 사유에 따라서 Choices를 만들어 두는 것도 한 가지 방법일 수 있다

(0 - 게시된 글
 1 - 사용자가 삭제한 게시글
 2 - 다수 사용자의 신고로 블라인드된 게시글
 3 - 운영원칙 위반으로 관리자가 삭제한 게시글)

뭐 이런거...

**Comment by jihoon-ko** [comment]
See Pull Request #199 
1. is_deleted 추가했습니다만 아직은 0(게시된 글)과 1(사용자가 삭제한 게시글)만 씁니다.
2. is_deleted가 1일 때 render를 다르게 할 수 있게 되었습니다.

**Comment by jihoon-ko** [comment]
![otl1](https://cloud.githubusercontent.com/assets/15546366/22627051/fe40cd76-ebfd-11e6-9dc4-f693f6ae633f.png)

**Comment by zealotzealot** [comment]
#196, #199
