### ISSUE TITLE
후기 삭제 기능

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#196]
비방성 발언 처리용 삭제 기능
후기 모델에 isDeleted 필드를 추가해서 이 값이 만약에 true이면 후기의 내용을 삭제되었습니다로 고치고, 수정 및 좋아요가 불가능하도록.

크게 두가지로 나뉘어집니다.
1. 모델 수정
2. 실제 후기 보여주는 페이지에서 스태틱으로 뜨게끔 하는 코드.

**Comment by jihoon-ko** [comment]
Issue #194와 Pull Request #199를 참고해 주세요.

**Comment by zealotzealot** [comment]
#199
