### ISSUE TITLE
과목사전 후기 개별 링크 자바스크립트가 아닌 a href 등으로 구현.

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#213]
과목사전 후기 목록에서 내용 클릭하면 자세한 후기 페이지로 가는데 여기서 ctrl + 클릭하면 새 탭으로 열려야 하는데 자바스크립트로 짜여져 있어서 그게 안됩니다..... a href 같은걸로 짭시다.

**Comment by zealotzealot** [comment]
리액트 변환으로 종료
