### ISSUE TITLE
김광년 이슈를 교수님 병합 없이 해결하는 방법

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#214]
김광년 이슈 (링크바람)를 해결하기 위해서 같은 교수님이 중복하여 나오는 경우 병합하자는 의견이 있었는데,

같은 교수님이라는 걸 판별하기가 어렵기 때문에 포기했었습니다.

근데 기존의 키워드 검색 방식인 혹시 이 교수님을 검색하셨나요? <교수님 이름>* 

방식을 바꿔서 교수님 이름 기준으로 검색한 결과를 리스트로 보여주고, 그 밑에 과목명 기준으로 검색한 결과를 보여준다면 더 자연스럽고 좋을 것 같습니다. 

둘 중 하나의 결과 리스트가 empty라면 아예 빼고 보여주는 것도 방법이겠습니다.

더 많이 쓰이는 검색기준(교수님/렉쳐이름 중)을 판단하여 그걸 디폴트로 하고 나머지 하나는 리스트를 접어두었다가 클릭하면 expand 하도록 바꾸는 방법도 있을 것 같습니다.\

코멘트로 다른 의견 있으면 제안해주세요. 다만 이 개선사항의 우선순위는 타임테이블 개발에 비해 매우 낮습니다.

**Comment by zealotzealot** [comment]
2020 리뉴얼로 해당 없음
