### ISSUE TITLE
후기작성 가이드라인 만들기

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#24]

**Comment by jihoon-ko** [comment]
1) 학점, 로드 등의 평가에 대하여 왜 그렇게 평가를 했는지 간단히 서술해주세요.
  ex) 진도를 빠르고 많이 나가는 경향이 있습니다 / 학점은 절대평가로 주셔서 잘 나온 것 같아요
        / 과제는 6번 주어졌고, 각 과제마다 시간이 약 6 ~ 8 시간 소요된 것 같습니다.
2) 최대한 본인의 감정을 배제해주시면 감사하겠습니다.
  ex) 교수님이 저를 맘에 안 들어하시는 것 같아요 (X) / 시험기간에 플젝 내준건 좀 너무하다싶었음 (X)
3) 나중에 이 수업을 들을 학생들을 위해 여러 조언들을 해 주세요.
  ex) 이 수업을 들으시려면 먼저 이산구조와 데이타구조를 먼저 듣고 오시는 것을 추천합니다.
        / 교수님이 수업하실 때 열심히 참여하시면 좋을 것 같아요

**Comment by jihoon-ko** [comment]
여기에 남기면 되나요??

**Comment by jihoon-ko** [comment]
백엔드에 가이드라인을 반영하였습니다.
조금의 수정이 있을지는 모르겠으나 일단 Close 하도록 하겠습니다.
