### ISSUE TITLE
[타임테이블] DB query 결과 캐싱

### ISSUE THREAD

**Issue by zealotzealot** [sparcs-kaist/otlplus#257]
과목을 검색할 때 DB query 결과를 캐싱하여 중복된 query를 여러번 보낼 필요가 없게 한다.

**Comment by jihoon-ko** [comment]
캐싱은 redis 같은 걸 쓰나요?

**Comment by zealotzealot** [comment]
테스트 결과 성능상 실효성이 크게 없어 취소합니다.
