### ISSUE TITLE
검색페이지 프론트엔드 수정

### ISSUE THREAD

**Issue by talkwithraon** [sparcs-kaist/otlplus#28]
아래는 담당 디자이너님의 수정 사항

데스크톱쪽 수정사항
1. 학과가 2줄로 되어있는데 줄 사이 간격을 좀 더 넓혀주세요! 학년과 학기 사이의 70%정도느낌으로
2. 검색창의 폭 줄이기 
3. (분류 학과 학년 학기) 폰트 두께와 색깔, 크기를 오른쪽 항목들과 같게해주세요
4. 체크박스 동그라미 두께 좀 더 얇게, 테두리 색깔 더 연하게 (#b0b0b0)
5. 글씨와 동그라미의 사이 간격(넓은부분 말고 좁은부분) 3px정도 더 넓혀주세요
6. 메인 사진이 위아래로 좀 더 넓었으면 좋겠어요, 지금보다 30%정도? 그리고 검색창+필터의 세로위치가 사진의 가운데정도였음 좋겠슴다. 필터 아래에도 사진이 조금 보이게
7. 필터 -> 옵션, 필터 글씨가 검색보다 위쪽에 위치한 것 같아요
8. 메인 사진을 제가 어둡게 수정했는데 이거를 제가 뽑아서 드린다는걸 깜빡해서 다시 드릴게요
9. 동그라미 안에 디데이 폰트 두께 한단계 얇게, 동그라미랑 폰트 전체적으로 조금만 더 크게하되 그렇게되면 오른쪽으로 너무 튀어나오니까, 지금은 동그라미의 중심이 정확히 오른쪽위 꼭지점에 있는데 동그라미의 중심을 그것보다 왼쪽아래로 4픽셀정도씩 옮겨주세요
10. 성적 널널 강의 종합 사이의 간격을 많이 좁혀주세요. 모바일이나 아이패드에서도 한줄안에 다 나와도 될 것 같아요
11. 과목명 쪽 폰트 한단계 얇게 부탁드려요. 
12. 폰트 색깔이 전체적으로 진한 것 같은데 필터쪽은 (#36363b) 과목명이랑 '사랑받는'은 (#4b4b4b) 과목후기 짜잘한 텍스트는 (#9c9c9c) 성적 널널 종합 이거는 (#5c5c5f)
13. 과목 제목과 후기 왼쪽마진 3픽셀정도 더 (네모랑 가까워서)

패드쪽은 성적 널널 강의 종합만 한줄로 나와도 괜찮을듯싶고

핸드폰쪽은 음 전용 ui를 만들지않으면 힘들것같네요

**Comment by jiggum** [comment]
작업진행/완료사항을 확인할수가없어서 우선닫아놓고 다음에 디자인자문받겠습니다.
