### ISSUE TITLE
후기 작성시 렉쳐, 코스, 교수 스코어 갱신

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#32]
코맨트/렉쳐, 코스,스코어
grade/ grade_sum
load / load_sum
speech/ speech_sum
total/ total_sum
/ comment_num
필드 갱신필요

**Comment by jihoon-ko** [comment]
이건 이미 되는 기능 아닌가요??

**Comment by zealotzealot** [comment]
지금은 Lecture만 갱신되는데 얼마전에 Course와 Professor에도 해당 필드가 추가되어 이 부분을 말하는 거 같네요

**Comment by zealotzealot** [comment]
47289d47a63c1b1dd77942aa7804358db488f9f2
