### ISSUE TITLE
로그인페이지

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#44]

**Comment by a1sams1a** [comment]
페이지가 굳이 필요한지 의문입니다.

**Comment by jiggum** [comment]
sso페이지로넘어가져야하는데, 중간에 login/session 텍스트만있는페이지로가지는거 수정원합니다.

**Comment by kangwon** [comment]
수정했습니다. 일단 주석처리만 해놨는데, 확인해 보시고 제대로 된 것 같다 싶으시면 제대로 삭제하겠습니다.

**Comment by jiggum** [comment]
학번 20150390 인유저 끌어와서 작동하게하는거 > 로그인한 유저로 작동하게끔 변경해야하는데, 스팍스sso 테스트계정 포탈계정연동문제, 로그인과정을 잘몰라서 건드리기그러네요.. 포탈 연동한 스팍스sso아이디로 , take_lecture_list 끌어오는것 세션쪽에서 해주시면감사하겠습니다.!

**Comment by jiggum** [comment]
아그리고 원래 로그인버튼> /session/ 페이지 > 스팍스sso로로그인 버튼있는페이지 > 스팍스 sso 에서
로그인버튼 > /session/페이지 > 스팍스 sso 로 변경됬는데,
/session/페이지도 안거치고 바로 넘어갔음좋겠습니다.

**Comment by isyangban** [comment]
세션 페이지 안 거치고 바로 넘어가게 하려면 login url을 /session이 아니라 /session/login 으로 url 바꾸면 될 것 같은데요? 이건 세션의 문제가 아닌 것 같습니다.

**Comment by jiggum** [comment]
강원님코멘트 바로밑에있는거는 그밑에코멘트와별개로 스팍스sso, 테스트계정말고 일반계정으로 사용항수있도록, 포탈sso 테이큰렉쳐리스트 데이터 가져오는것 말하는겁니다.!

**Comment by jiggum** [comment]
f0c017bf602966c329f9e001ccd396dcaa025ac1
로그인페이지 > 스팍스SSO 페이지이용,
로그인기능 완료
