### ISSUE TITLE
잘못된  url 로 접근시 에러  or  검색결과가 없습니다 페이지 뜨게끔

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#46]

**Comment by jihoon-ko** [comment]
제가 미적 감각이 없어서(?) 404 view를 매우 간단히 만들어 놓았습니다. 다만 Debug 모드를 False로 바꿔야 이 뷰가 보이게 됩니다.

**Comment by jihoon-ko** [comment]
조금 있다가 업로드하도록 하겠습니다

**Comment by jiggum** [comment]
생각해보니 디버그모드 False로하면 오류메세지 못보는것아닌가요? 완개발이후에 바꿔주세요!

**Comment by a1sams1a** [comment]
404뿐만 아니라 400, 403, 500에 대해서도 만들면 좋을거 같아요!
