### ISSUE TITLE
코스/교수박스 한줄평 업데이트

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#49]
http://bulletin.kaist.ac.kr/html/kr/?year=2014&id=kr20141303&file=E

**Comment by jihoon-ko** [comment]
pdf 문서에서 text를 복사한 데이터를 이용해 만들 수 있는 간단한 파서를 만들어보았습니다.
(단, 과목이 바뀌면 개행이 되어있어야 합니다.)
본인의 환경에 맞게 바꿔서 사용하시면 될 것 같습니다.
파서 파일과 데이터 예시는 bit.sparcs.org 서버의 /home/mango/parser에 있으니 참고하세요 :)

**Comment by jiggum** [comment]
완료 38d16a9 
update_course_summury.py 안에서 파싱할 txt경로지정해줘야함!
