### ISSUE TITLE
Session views.py 에서 동명이인 처리 관련 문제

### ISSUE THREAD

**Issue by jihoon-ko** [sparcs-kaist/otlplus#68]
소스를 읽어본 결과 동명이인 처리가 되지 않는 것으로 확인됩니다.
username으로 사람을 체크하지 않고, sid(사람마다 고유한 값)을 이용하여 체크를 하는 것이 필요할 것 같습니다

**Comment by jiggum** [comment]
49e614f749a187f64da729ee9ac452681445f7fa
