### ISSUE TITLE
로그아웃아직도안되요

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#75]

**Comment by jihoon-ko** [comment]
그거 두 번 정도 하면 로그아웃 되던데... 그 이유를 잘 모르겠네여 ㅋㅋㅋㅋㅋ

**Comment by a1sams1a** [comment]
API 다시 확인해보겠습니다. 근데... 서버시간.... 올바른가요...?
서버시간이 느리거나 빠르면 로그아웃이 안됩니다.

**Comment by a1sams1a** [comment]
방금 심심해서 ntp 설치하고 서버 시간 맞춰봤는데 잘 되는거 같네요. 확인하고 아직도 문제 있으면 태그해주세요.
