### ISSUE TITLE
과목 코멘트 1개 보는 페이지에서 글 클릭하면 자기 자신으로 다시 이동

### ISSUE THREAD

**Issue by jo1996jo** [sparcs-kaist/otlplus#76]
글 내용을 클릭하면 다시 그 페이지로 이동해서 뒤로가기를 계속해서 눌러야 목록으로 이동 가능

**Comment by jiggum** [comment]
네이버도 그럽니다..!
요거고치기시작하면 밑도끝도없어서 보류할게요(현재페이지 링크포함하는 모든곳 고쳐야되므로..)
