### ISSUE TITLE
강의 제목이 너무 길 때 교수명이랑 년도가 생략되어 보이지 않음

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#80]
<img width="1280" alt="2016-06-01 11 56 12" src="https://cloud.githubusercontent.com/assets/15705385/15716963/cb6feca4-285f-11e6-8ad4-4baaeb4f8a92.png">

**Comment by jiggum** [comment]
3b733bc 
렉쳐명 아래로 내렸어요
