### ISSUE TITLE
후기 작성 텍스트 에어리어 크기 조절 가능한 문제(조절 불가능하게 바꾸기)

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#82]
후기 작성 페이지에서 작성 에어리어의 크기를 조절 가능해 성적 체크 파트를 침범할 수 있습니다. 

에어리어 크기 조절이 임의로 불가능하게 할 필요가 있어 보입니다.

**Comment by jiggum** [comment]
크기조절불가능 + 스크롤 설정변경했습니다.!
