### ISSUE TITLE
로그인 시 500 에러

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#84]
일부 사용자에 한해(에러 조건은 불명 아직) 로그인 시 500 에러가 발생하고 로그아웃 후 재로그인을 하려고 해도

계속 같은 아이디로만 로그인을 시도하여 직접 sso 페이지에 접속, 로그아웃 후 다른 계정으로 재시도를 해야 되는 불편도 있음.

**Comment by isyangban** [comment]
만약 스팍스 sso 로그인이 되어있다면, 계속 같은 아이디로만 로그인을  하는 것은 의도된 것으로 알고있어요.

**Comment by jiggum** [comment]
1. 우선 첫로그인시 발생하는 에러는 해결했습니다. default 파일실행주소가 이상한데로설정되있었어요..
2. "일부 사용자에 한해(에러 조건은 불명 아직) 로그인 시 500 에러가 발생하고 로그아웃 후 재로그인을 하려고 해도 계속 같은 아이디로만 로그인을 시도하여 직접 sso 페이지에 접속, 로그아웃 후 다른 계정으로 재시도를 해야 되는 불편도 있음."  요건 이전까지 불완전한상태에서가입한유저들에한해, UserProfile이 생성되지않아 발생했습니다.. UserProfile 없는 유저들 다 삭제조치했고요. 이후에혹시 더발생한다면.. 다시이슈열어주세요
