### ISSUE TITLE
과목 후기 업로드할 때 팝업창 띄우는 이슈

### ISSUE THREAD

**Issue by sparcsJara** [sparcs-kaist/otlplus#85]
otl  과목 후기 업로드해도 refresh만 되서 올라갔는지 실감하기 어려움. 팝업창(아마 더 좋은 방법이 있을 듯하다) 같은거라도 띄어주면 좋을 듯.

**Comment by heejongahn** [comment]
- 업로드 되는 동안 스피너가 돌아가게 한 뒤 완료되면 없앤다
- 완료 후 적절한 (성공, 필수 필드 작성 요청, ...) 플래시 메세지를 띄운다

등도 좋은 방법이 될 수 있을 것 같습니다. 개인적으로는 그냥 둘 다 하면 될거같네용
