### ISSUE TITLE
Service Worker에 index.html이 캐시되는 문제

### ISSUE THREAD

**Issue by zealotzealot** [sparcs-kaist/otlplus#856]
몇달 전에 service worker를 도입했는데 index.html이 캐시되어 otl 업데이트 후 로딩이 제대로 되지 않는 문제가 발생합니다.
react 특성상 빌드할 때마다 js와 css 파일에는 자동으로 random string을 붙여 캐시가 refresh되도록 해 주는데, index.html은 이렇게 할 수 없어 발생하는 문제 같습니다.

**Comment by GrasshopperBears** [comment]
dependency가 추가되는 문제가 있긴 하지만 [다음과 같은 해결 방법](https://www.huskyhoochu.com/how-to-migrate-workbox/)도 존재해보입니다.

**Comment by zealotzealot** [comment]
> dependency가 추가되는 문제가 있긴 하지만 [다음과 같은 해결 방법](https://www.huskyhoochu.com/how-to-migrate-workbox/)도 존재해보입니다.

괜찮네요. 그정도 dependency 추가는 감수할 수 있을 것 같습니다.

**Comment by zealotzealot** [comment]
#858 일단 해결된 것 같습니다.
