### ISSUE TITLE
학년 필터링 문제 수정

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/otlplus#884]
- [ ] 학년 (몇백번대) 과목 필터링이 제대로 되지 않는 문제를 수정한다.
![검색](https://user-images.githubusercontent.com/34625313/146540227-9140a670-4540-4fa0-8e2d-ad34e1cb3f85.png)

**Comment by zealotzealot** [comment]
학년 필터가 백엔드에서는 'level'로 받는데 프론트에서는 'grade'로 보내네요. 그래서 필터 자체가 적용이 안된 것 같습니다
