### ISSUE TITLE
좋아요 나타내는부분 정렬

### ISSUE THREAD

**Issue by jiggum** [sparcs-kaist/otlplus#9]
현재 왼쪽정렬되있어서 보기안좋아요 + 제외한 숫자부분 정렬필요!

**Comment by talkwithraon** [comment]
@jiggum 추천 수가 00개 일 때와 0개 일 때 차별을 줄까요? 별로 예쁘게 안나오는데... 좋은 아이디어 부탁드려요! 아래 이미지 확인해보세요!

https://pbs.twimg.com/media/CZ5gJEHVAAESszM.png:large

**Comment by jiggum** [comment]
https://scontent.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/12645016_891916824255081_8176486493394853887_n.jpg?oh=71d9877ca75e4fd5d602707ee3923618&oe=5723BDF7

+99 는 raon님 커밋전 상태구요,
+9는 +99의 +위치그대로, +와 숫자사이에 스페이스 넣은건데,
이것처럼 template tag로 10보다작을때 처리하면어떨까요?
100이상은 99로 처리하고요.

**Comment by ashe-sparcs** [comment]
그냥 가운데 정렬하는건 보기 안좋을까요?

**Comment by jiggum** [comment]
가운데정렬하면 +위치가 왔다갔다해서..
2016. 1. 30. 오후 2:00에 "Kim, Jae-Sung" <notifications@github.com>님이 작성:

**Comment by talkwithraon** [comment]
저번 회의 때 얘기 끝난걸로...
