### ISSUE TITLE
키워드 검색 결과 페이지에서 강의 제목 마우스 호버시 불도 안들어오고 손가락 모양도 안됨.

### ISSUE THREAD

**Issue by ashe-sparcs** [sparcs-kaist/otlplus#90]
멍청도식 스크린샷 참조(지역비하의 의도 없습니다)
![kakaotalk_photo_2016-06-05-16-22-20](https://cloud.githubusercontent.com/assets/15705385/15804141/b430bac8-2b39-11e6-9279-884c1f230430.jpeg)

**Comment by ashe-sparcs** [comment]
죄송합니다 제가 발로 짠듯

**Comment by jiggum** [comment]
마우스올리면 밑에그림자색바끼구요,
손가락모양으로수정했습니다.
