### ISSUE TITLE
교수님 이름으로 키워드 검색 시 동일한 교수님이 통합되지 않고 나뉘어 여러번 나오는 문제

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/otlplus#97]
스크린샷을 참조해주세요.
<img width="1280" alt="default" src="https://cloud.githubusercontent.com/assets/15705385/16649081/1265ea86-4472-11e6-938a-5b448eb35d0d.png">

**Comment by zealotzealot** [comment]
#214
